name: Generate Sitemap

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate sitemap.xml
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: '/'  # Leave as '/' unless your site is in a subfolder
          sitemap-format: xml

      - name: Push sitemap.xml
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Auto-update sitemap" || echo "No changes to commit"
          git push
