name: Generate Sitemap

on:
  push:
    branches:
      - main  # Change if your branch is not main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: '/'  # use '/' unless your site is in a subfolder
          sitemap-format: xml
